### ISSUE TITLE
top

### ISSUE THREAD

**Issue by utya1988** [uboborov/ffmpeg_h264_H3#1]
Добрый день. Хотел узнать, какая загрузка процессора Allwinner H3? и можете ли вы протестировать ещё на rtsp?

**Comment by uboborov** [comment]
Здравствуйте. Я не измерял загрузку при работе кодека, но не думаю что большая, ведь он аппаратный. Боюсь, что в ближайшее время я этим заниматься не буду.

**Comment by uboborov** [comment]
у меня 10.3% максимальная загрузка А20, но это больше зависит от конкретного прииложения
